"""Add source domain to user.

Revision ID: 81dfcb4305c1
Revises: f36d15d8e86f
Create Date: 2021-09-06 01:20:38.482023

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "81dfcb4305c1"
down_revision = "f36d15d8e86f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("link")
    op.add_column(
        "user", sa.Column("source_domain", sa.String(length=100), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "source_domain")
    op.create_table(
        "link",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "date_opened", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="link_pkey"),
    )
    # ### end Alembic commands ###
